"""Cross-implementation parity tests for request building.

The golden file was generated by encoding the same logical searches with the
original reference implementation (him229/stays), whose output is known to be
accepted by the live endpoint. Byte-identical payloads here mean wire
compatibility without a network round-trip.
"""

import json
from datetime import date
from pathlib import Path

import pytest

from ghotels.errors import MissingEntityKeyError
from ghotels.models import (
    Amenity,
    Brand,
    Currency,
    Guests,
    Location,
    MinRating,
    PropertyType,
    SearchFilters,
    SortBy,
    StayDates,
)
from ghotels.protocol import build_detail_payload, build_search_payload, encode_form_body

GOLDENS = json.loads(
    (Path(__file__).parent.parent / "fixtures" / "request_goldens.json").read_text()
)

SEARCH_CASES = {
    "minimal": SearchFilters(location=Location(query="tokyo hotels")),
    "dates_only": SearchFilters(
        location=Location(query="paris, france hotels"),
        dates=StayDates(check_in=date(2026, 9, 1), check_out=date(2026, 9, 4)),
    ),
    "kitchen_sink": SearchFilters(
        location=Location(query="new york hotels"),
        dates=StayDates(check_in=date(2026, 7, 22), check_out=date(2026, 7, 26)),
        guests=Guests(adults=3, child_ages=[7, 12]),
        currency=Currency.EUR,
        property_type=PropertyType.HOTELS,
        sort_by=SortBy.LOWEST_PRICE,
        amenities=[Amenity.POOL, Amenity.WIFI],
        brands=[Brand.HILTON],
        star_classes=[5, 4],
        price_min=100,
        price_max=300,
        min_rating=MinRating.FOUR_ZERO_PLUS,
        free_cancellation=True,
        eco_certified=True,
        special_offers=True,
    ),
    "special_offers_no_rating": SearchFilters(
        location=Location(query="london hotels"),
        special_offers=True,
    ),
    "price_max_only": SearchFilters(
        location=Location(query="rome hotels"),
        price_max=150,
    ),
    "four_seasons_bare_brand": SearchFilters(
        location=Location(query="miami hotels"),
        brands=[Brand.FOUR_SEASONS],
    ),
    "pinned_location": SearchFilters(
        location=Location(
            query="hotels",
            kgmid="/m/05qtj",
            fid="0x479f8e1:0x8c92a1",
            display_name="Paris",
        ),
        dates=StayDates(check_in=date(2026, 9, 1), check_out=date(2026, 9, 4)),
    ),
    "one_adult": SearchFilters(
        location=Location(query="berlin hotels"),
        guests=Guests(adults=1),
    ),
    "sort_highest_rating": SearchFilters(
        location=Location(query="sydney hotels"),
        sort_by=SortBy.HIGHEST_RATING,
        min_rating=MinRating.FOUR_FIVE_PLUS,
    ),
    "relevance_sort_is_null": SearchFilters(
        location=Location(query="oslo hotels"),
        sort_by=SortBy.RELEVANCE,
    ),
    "vacation_rentals": SearchFilters(
        location=Location(query="lake tahoe cabins"),
        property_type=PropertyType.VACATION_RENTALS,
    ),
}


@pytest.mark.parametrize("name", sorted(SEARCH_CASES))
def test_search_payload_matches_reference(name):
    assert build_search_payload(SEARCH_CASES[name]) == GOLDENS[name]


def test_detail_payload_matches_reference():
    payload = build_detail_payload(
        "ChkI-example-entity-key",
        dates=StayDates(check_in=date(2026, 7, 22), check_out=date(2026, 7, 26)),
        currency=Currency.USD,
    )
    assert payload == GOLDENS["detail_mode"]


def test_encoded_body_matches_reference():
    body = encode_form_body(build_search_payload(SEARCH_CASES["minimal"]))
    assert body.decode() == GOLDENS["_encoded_minimal_body"]


def test_detail_payload_rejects_empty_entity_key():
    dates = StayDates(check_in=date(2026, 7, 22), check_out=date(2026, 7, 26))
    with pytest.raises(MissingEntityKeyError):
        build_detail_payload("", dates=dates)
    with pytest.raises(MissingEntityKeyError):
        build_detail_payload("   ", dates=dates)


def test_detail_payload_carries_guests_in_party_block():
    """Occupancy must reach the wire — the original project dropped it (fix PR #7)."""
    payload = build_detail_payload(
        "ChkI-example-entity-key",
        dates=StayDates(check_in=date(2026, 7, 22), check_out=date(2026, 7, 26)),
        guests=Guests(adults=3, child_ages=[7]),
    )
    party_block = payload[1][1]
    assert party_block == [[[3], [3], [3], [2, 12]], 1]
    child_count = payload[1][2][1][5]
    assert child_count == [None, 1]
